apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microblog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microblog.name" . }}
    helm.sh/chart: {{ include "microblog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microblog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: microblog
  template:
    metadata:      
      labels:
        app.kubernetes.io/name: {{ include "microblog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: microblog
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microblog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.microblog.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.microblog.image.repository }}:{{ .Values.microblog.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.microblog.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          {{- if .Values.microblog.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end  }}
          env:
            {{- if .Values.external.enabled }}
            - name: DATABASE_URL
              value: {{ .Values.external.databaseHost | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.external.databasePort | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.external.databaseName | quote }}
            - name: DATABASE_USER
              value: {{ .Values.external.databaseUser | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.external.databasePassword | quote }}
            {{- else if .Values.mysql.enabled }}
            - name: DATABASE_URL
              value: {{ include "microblog.databaseHost" . | quote }}
            - name: DATABASE_PORT_NUMBER
              value: {{ include "microblog.databasePort" . | quote }}
            - name: DATABASE_NAME
              value: {{ include "microblog.databaseName" . | quote }}
            - name: DATABASE_USER
              value: {{ include "microblog.databaseUser" . | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "microblog.databaseSecretName" . }}
                  key: {{ include "microblog.databasePasswordKey" . | quote }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: {{ include "microblog.redisHost" . | quote }}
            - name: REDIS_PORT
              value: {{ .Values.external.redisPort | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "microblog.redisSecretName" . }}
                  key: {{ include "microblog.redisPasswordKey" . | quote }}
            {{- end }}
            - name: ELASTICSEARCH_URL
              value: {{ include "microblog.elasticsearchHost" . | quote }}
            - name: MICROBLOG_EMAIL
              value: {{ .Values.Email | quote }}
            {{- if .Values.microblog.smtpHost }}
            - name: SMTP_HOST
              value: {{ .Values.microblog.smtpHost | quote }}
            {{- end }}
            {{- if .Values.microblog.smtpPort }}
            - name: SMTP_PORT
              value: {{ .Values.microblog.smtpPort | quote }}
            {{- end }}
            {{- if .Values.microblog.smtpUser }}
            - name: SMTP_USER
              value: {{ .Values.microblog.smtpUser | quote }}
            {{- end }}
            {{- if .Values.microblog.smtpPassword }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "microblog.secretName" . }}
                  key: smtp-password
            {{- end }}
            {{- if .Values.microblog.smtpProtocol }}
            - name: SMTP_PROTOCOL
              value: {{ .Values.microblog.smtpProtocol | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.microblog.resources | nindent 12 }}
      
