{{- if not or .Values.mariadb.enabled .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "microblog.fullname" . }}-external"
  labels: 
    app.kubernetes.io/name: {{ include "microblog.name" . }}
    helm.sh/chart: {{ include "microblog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  redis-password: {{ default "" .Values.externalRedis.password | b64enc | quote }}
{{- end }}
