{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "microblog.fullname" . }}-microblog
  labels: 
    app.kubernetes.io/name: {{ include "microblog.name" . }}
    helm.sh/chart: {{ include "microblog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.persistence.annotations }}
  annotations:
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.hostPath }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "drupal.storageClass" . | nindent 2 }}
{{- end -}}
