apiVersion: v1
kind: Service
metadata:
  name: { { include "microblog.fullname" . } }
  labels: { { - include "microblog.labels" . | nindent 4 } }
spec:
  type: { { .Values.microblog.service.type } }
  ports:
    - port: { { .Values.microblog.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "microblog.selectorLabels" . | nindent 4 } }
